#Datenbankeinstellungen
database.url=jdbc:mariadb://87.106.133.140:3306/TischtennisBerichtTest
database.user=michaelremote
database.passwort=FUEMM638UgYvtR2DZAh1jNiJBZOoq6Wezok/m1E8r5ApnkgYRJ5fSlrqUR7S7w72c/tYFVcfg7H7TfbsgOO9eQ==

